---
- name: Installation de Docker sur l'EC2 Ubuntu
  hosts: dev
  become: yes
  tasks:
    - name: Mettre à jour les paquets
      apt:
        update_cache: yes
        upgrade: dist

    - name: Installer les dépendances
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Ajouter la clé GPG Docker
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Ajouter le dépôt Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Installer Docker Engine
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Démarrer et activer Docker
      systemd:
        name: docker
        enabled: yes
        state: started
