- name: Mise à jour de la configuration Prometheus avec node_exporter
  hosts: dev
  become: yes

  vars:
    prometheus_path: /home/ubuntu/prometheus

  tasks:
    - name: Copier le nouveau prometheus.yml
      copy:
        src: "../../monitoring/prometheus/prometheus.yml"
        dest: "{{ prometheus_path }}/prometheus.yml"
        mode: '0644'

    - name: Redémarrer le container Prometheus avec la nouvelle configuration
      docker_container:
        name: prometheus
        image: custom-prometheus
        state: started
        recreate: true
        restart_policy: always
        published_ports:
          - "9090:9090"
        volumes:
          - "{{ prometheus_path }}/prometheus.yml:/etc/prometheus/prometheus.yml"
